export const TOGGLE_IS_COMMENT_POSTING = "TOGGLE_IS_COMMENT_POSTING";
export const TOGGLE_IS_COMMENT_POSTING_SUCCESS =
  "TOGGLE_IS_COMMENT_POSTING_SUCCESS";
export const TOGGLE_IS_ERROR_WHILE_POSTING_COMMENT =
  "TOGGLE_IS_ERROR_WHILE_POSTING_COMMENT";
export const GET_COMMENTS = "GET_COMMENTS";
export const RESET_ALL_STATUS = "RESET_ALL_STATUS";
export const ADD_LIKE_TO_COMMENT = "ADD_LIKE_TO_COMMENT";
export const ADD_DISLIKE_TO_COMMENT = "ADD_DISLIKE_TO_COMMENT";
