export const TOGGLE_IS_POSTING = "TOGGLE_IS_POSTING";
export const TOGGLE_IS_POSTING_SUCCESS = "TOGGLE_IS_POSTING_SUCCESS";
export const TOGGLE_IS_ERROR_WHILE_POSTING = "TOGGLE_IS_ERROR_WHILE_POSTING";
export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const ADD_LIKE_TO_QUESTION = "ADD_LIKE_TO_QUESTION";
export const ADD_DISLIKE_TO_QUESTION = "ADD_DISLIKE_TO_QUESTION";
