export const IS_SIGNUP_SUCCESS = "IS_SIGNUP_SUCCESS";
export const IS_SIGNUP_FAILED = "IS_SIGNUP_FAILED";
export const TOGGLE_IS_POSTING = "TOGGLE_IS_POSTING";
export const LOG_IN_SUCCESSFUL = "LOG_IN_SUCCESSFUL";
export const LOG_IN_FAILED = "LOG_IN_FAILED";
export const RESET_IS_FAILED = "RESET_IS_FAILED";
export const LOGOUT = "LOGOUT";